### PR TITLE
IDUG Charlotte Lab

### PR DESCRIPTION
**Pull request by MikeBauerCA**
Add lab content from IDUG Charlotte

### CODE REVIEW

**Comment by solsu01** [comment]
@MikeBauerCA could you change all bright commands to zowe commands?

**Comment by MikeBauerCA** [comment]
Done, thank you for your review!

**Comment by chipset** [comment]
If we are changing references to ZOWE, should we not change the repo name, too?

**Comment by MikeBauerCA** [comment]
We could but it would break links to this repository. We also have https://github.com/zowe/zowe-cli-sample-scripts. Once Zowe finalizes the conformance program, much of this content can move there. This space could be reserved for scripts that use commands not yet generally available in Zowe.

**Pull request merged**
